spring:
  application:
    name: moodipie
  main:
    allow-bean-definition-overriding: true
  config:
    import:
      - classpath:spotify.yml
  profiles:
    active: dev
server:
  error:
    include-exception: false
    include-stacktrace: never
    include-message: never
    include-binding-errors: never
    path: /error
