spring:
  application:
    name: moodipie
  main:
    allow-bean-definition-overriding: true
  config:
    import: spotify.yml
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
  datasource:
    url: jdbc:tc:mysql:8.0.36://cow/mydatabase?   //이거고치기
    username: myuser
    password: secret
    driver-class-name: com.mysql.cj.jdbc.Driver
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
