spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydatabase
    username: root
    password: '0000'
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
jwt:
  secret: eW91ci1zZWNyZXQta2V512311321fdds23eqw32eqw2323wq2323qe32e3223w2e2wrg2fsd3f3x2gh3fzdfzd3f22f
  expire-ms: 3600000

  access:
    expiration: 80
    header: Authorization

  refresh:
    expiration: 90
    header: Authorization-refresh
cors:
  allowed-origins:
    - http://localhost:5173

